const translations = {
  "en": {
    "const_test": "const_test",
    "const_test2": "const_test2",
    "Current locale: %{var0}": "Current locale: %{var0}",
    "deploy_now": "deploy_now",
    "examples": "examples",
    "get_started_by_editing": "get_started_by_editing",
    "go_to_nextjs": "go_to_nextjs",
    "learn": "learn",
    "read_our_docs": "read_our_docs",
    "save_and_see_changes_instantly": "save_and_see_changes_instantly",
    "src/app/page.tsx": "src/app/page.tsx",
    "Test Server Component I18n": "Test Server Component I18n",
    "test_new_mark_field": "test_new_mark_field",
    "Welcome to Edgen Private Beta, anon! Drop your invite code below to unlock Alpha before everyone else.": "Welcome to Edgen Private Beta, anon! Drop your invite code below to unlock Alpha before everyone else."
  },
  "ko": {
    "const_test": "const_test",
    "const_test2": "const_test2",
    "Current locale: %{var0}": "현재 로케일: %{var0}",
    "deploy_now": "지금 배포하기",
    "examples": "예시",
    "get_started_by_editing": "편집하여 시작하기",
    "go_to_nextjs": "다음 단계로 이동: Next.js",
    "learn": "배우다",
    "read_our_docs": "문서를 읽어보세요",
    "save_and_see_changes_instantly": "변경 사항을 즉시 저장하고 확인하세요",
    "src/app/page.tsx": "src/app/page.tsx",
    "Test Server Component I18n": "테스트 서버 컴포넌트 I18n",
    "test_new_mark_field": "테스트_신규_마크_필드",
    "Welcome to Edgen Private Beta, anon! Drop your invite code below to unlock Alpha before everyone else.": "Edgen 프라이빗 베타에 오신 것을 환영합니다, 익명님! 초대 코드를 아래에 입력하여 다른 사람들보다 먼저 알파 버전을 잠금 해제해 보세요."
  },
  "zh-Hans": {
    "const_test": "常量测试",
    "const_test2": "常量测试2",
    "Current locale: %{var0}": "当前区域设置：%{var0}",
    "deploy_now": "立即部署",
    "examples": "示例",
    "get_started_by_editing": "通过编辑开始",
    "go_to_nextjs": "前往 Next.js",
    "learn": "学习",
    "read_our_docs": "阅读我们的文档",
    "save_and_see_changes_instantly": "立即保存并查看更改",
    "src/app/page.tsx": "src/app/page.tsx",
    "Test Server Component I18n": "测试服务器组件国际化",
    "test_new_mark_field": "测试新标记字段",
    "Welcome to Edgen Private Beta, anon! Drop your invite code below to unlock Alpha before everyone else.": "欢迎来到 Edgen 私密测试，匿名用户！在下方输入你的邀请码，抢先解锁 Alpha 版本。"
  },
  "zh-Hant": {
    "const_test": "常數測試",
    "const_test2": "常數測試2",
    "Current locale: %{var0}": "目前的地區設定：%{var0}",
    "deploy_now": "立即部署",
    "examples": "例子",
    "get_started_by_editing": "通過編輯開始",
    "go_to_nextjs": "前往Next.js",
    "learn": "學習",
    "read_our_docs": "閱讀我們的文件",
    "save_and_see_changes_instantly": "立即儲存並查看變更",
    "src/app/page.tsx": "src/app/page.tsx",
    "Test Server Component I18n": "測試伺服器組件 I18n",
    "test_new_mark_field": "測試新標記欄位",
    "Welcome to Edgen Private Beta, anon! Drop your invite code below to unlock Alpha before everyone else.": "歡迎來到 Edgen 私人測試版，匿名者！在其他人之前解鎖 Alpha 版本，請在下方輸入邀請碼。"
  },
  "vi": {
    "const_test": "const_test",
    "const_test2": "const_test2",
    "Current locale: %{var0}": "Bản địa hiện tại: %{var0}",
    "deploy_now": "triển_khai_ngay",
    "examples": "ví dụ",
    "get_started_by_editing": "Bắt đầu bằng cách chỉnh sửa",
    "go_to_nextjs": "chuyển_sang_nextjs",
    "learn": "học",
    "read_our_docs": "đọc_tài_liệu_của_chúng_tôi",
    "save_and_see_changes_instantly": "lưu_ và_ xem_ thay_ đổi_ ngay_ lập_ tức",
    "src/app/page.tsx": "src/app/page.tsx",
    "Test Server Component I18n": "Kiểm tra thành phần máy chủ I18n",
    "test_new_mark_field": "kiểm_tra_trường_đánh_dấu_mới",
    "Welcome to Edgen Private Beta, anon! Drop your invite code below to unlock Alpha before everyone else.": "Chào mừng bạn đến với Edgen Private Beta, anon! Nhập mã mời của bạn bên dưới để mở khóa Alpha trước tất cả mọi người."
  },
  "es": {
    "const_test": "const_test",
    "const_test2": "const_test2",
    "Current locale: %{var0}": "Configuración regional actual: %{var0}",
    "deploy_now": "desplegar_ahora",
    "examples": "ejemplos",
    "get_started_by_editing": "comience_editando",
    "go_to_nextjs": "ir_a_nextjs",
    "learn": "aprender",
    "read_our_docs": "leer_nuestra_documentación",
    "save_and_see_changes_instantly": "guarda_y_observa_los_cambios_inmediatamente",
    "src/app/page.tsx": "src/app/page.tsx",
    "Test Server Component I18n": "Prueba del componente del servidor I18n",
    "test_new_mark_field": "prueba_campo_nueva_marca",
    "Welcome to Edgen Private Beta, anon! Drop your invite code below to unlock Alpha before everyone else.": "¡Bienvenido a la beta privada de Edgen, anon! Deja tu código de invitación a continuación para desbloquear Alpha antes que todos los demás."
  },
  "tr": {
    "const_test": "const_test",
    "const_test2": "const_test2",
    "Current locale: %{var0}": "Geçerli yerel ayar: %{var0}",
    "deploy_now": "şimdi_dağıt",
    "examples": "örnekler",
    "get_started_by_editing": "Düzenleyerek başlayın",
    "go_to_nextjs": "go_to_nextjs",
    "learn": "öğrenmek",
    "read_our_docs": "belgelerimizi_okuyun",
    "save_and_see_changes_instantly": "değişiklikleri kaydet ve anında gör",
    "src/app/page.tsx": "src/app/page.tsx",
    "Test Server Component I18n": "Test Server Bileşeni I18n",
    "test_new_mark_field": "test_new_mark_field",
    "Welcome to Edgen Private Beta, anon! Drop your invite code below to unlock Alpha before everyone else.": "Edgen Özel Beta'ya hoş geldin, anon! Alfa'yı herkesden önce açmak için davet kodunu aşağı bırak."
  },
  "fr": {
    "const_test": "const_test",
    "const_test2": "const_test2",
    "Current locale: %{var0}": "Paramètres régionaux actuels : %{var0}",
    "deploy_now": "déployer_maintenant",
    "examples": "exemples",
    "get_started_by_editing": "Commencer par modifier",
    "go_to_nextjs": "aller_à_nextjs",
    "learn": "apprendre",
    "read_our_docs": "lire_nos_docs",
    "save_and_see_changes_instantly": "enregistrer_et_voir_les_modifications_en_instantané",
    "src/app/page.tsx": "src/app/page.tsx",
    "Test Server Component I18n": "Tester le composant du serveur I18n",
    "test_new_mark_field": "test_nouveau_champ_marque",
    "Welcome to Edgen Private Beta, anon! Drop your invite code below to unlock Alpha before everyone else.": "Bienvenue dans la version bêta privée d'Edgen, anon ! Saisissez votre code d'invitation ci-dessous pour débloquer l'Alpha avant tout le monde."
  }
};

export default translations;
