const metadataTranslations = {
  en: {
    "site.title": "Create Next App",
    "site.description": "Generated by create next app",
  },
  "zh-CN": {
    "site.title": "创建 Next 应用",
    "site.description": "由 create next app 生成",
  },
  "zh-TC": {
    "site.title": "創建 Next 應用",
    "site.description": "由 create next app 生成",
  },
  ko: {
    "site.title": "Next 앱 만들기",
    "site.description": "create next app으로 생성됨",
  },
  es: {
    "site.title": "Crear Aplicación Next",
    "site.description": "Generado por create next app",
  },
  de: {
    "site.title": "Next App Erstellen",
    "site.description": "Erstellt mit create next app",
  },
  tr: {
    "site.title": "Next Uygulaması Oluştur",
    "site.description": "create next app ile oluşturuldu",
  },
  vi: {
    "site.title": "Tạo Ứng Dụng Next",
    "site.description": "Được tạo bởi create next app",
  },
};

export default metadataTranslations;
